Paple/bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('logout/', views.logout, name='logout'),
    path('board/', views.board, name='board'),
    path('board/<int:post_id>/', views.detail, name='detail'),
    path('board/<int:post_id>/comment/', views.comment_register, name='comment_register'),
    path('board/<int:post_id>/update/', views.post_update, name='post_update'),
    path('board/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('board/register/', views.post_register, name='post_register'),
    path('board/register2/<int:q_id>', views.post_register2, name='post_register2'),
    path('board/<int:q_id>/register/', views.question_register, name='question_register'),
    path('board/<str:q_date>/register2/', views.question_register2, name='question_register2')
]

Paple/group/urls.py
from django.urls import path
from . import views

app_name = 'group'

urlpatterns = [
    path('group_main/', views.group_main, name="group_main"),
    path('modify/', views.group_modify, name="group_modify"),
    path('group_signin/', views.group_signin, name="group_signin"),
    path('group_login/', views.group_login, name="group_login"),
    path('group_del_member/<int:user_id>/', views.group_del_member, name="group_del_member")
]

Paple/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('bbs/', include('bbs.urls')),
    path('account/', include('account.urls')),
    path('group/', include('group.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Paple/group/models.py
from django.db import models

# Create your models here.

Paple/group/forms.py
from django import forms
from account.models import Group
from group.custom_widgets import PreviewImageFileWidget


class ModifyGroupInfoForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['group_name', 'group_img', 'group_code']
        labels = {
            'group_name': 'Group Name',
            'group_img': 'Group Image',
            'group_code': 'Group Code'
        }
        widgets = {
            'group_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'group_img': PreviewImageFileWidget(),
            'group_code': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'readonly': True
                }
            )
        }


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ['group_name', 'group_code']

        labels = {
            'group_name': '그룹명',
            'group_code': '그룹 코드'
        }

        widgets = {
            'group_name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'group_code': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'readonly': True
                }
            )
        }

Paple/group/views.py
from django.shortcuts import render, get_object_or_404, redirect
from account.models import Member, Group
from bbs.models import Post, Comment
from group.forms import ModifyGroupInfoForm, GroupForm
import uuid
import base64
import codecs


def group_main(request):
    return render(request, 'group/group_main.html')


def group_login(request):
    if request.method == "POST":

        # 초대 코드를 통해 그룹 찾기
        val = request.POST.get("invite_code")
        try:
            group = Group.objects.get(group_code=val)
        except Group.DoesNotExist:
            return render(request, 'group/group_main.html', {
                'message': '초대 코드가 잘못됐습니다.'
            })

        user_email = request.session['loginObj']
        member = Member.objects.get(user_email=user_email)
        member.group_code = group
        member.user_status = True
        member.save()

        return redirect('bbs:main')


def group_signin(request):
    user_email = request.session['loginObj']
    member = Member.objects.get(user_email=user_email)
    invite_code = generate_random_slug_code()
    new_group = Group(group_name='default', group_code=invite_code)

    if request.method == "POST":
        form = GroupForm(request.POST, instance=new_group)
        if form.is_valid():
            # Group 정보 수정
            form.save()
            
            # Member 정보 수정
            group = Group.objects.get(group_code=form.cleaned_data['group_code'])
            member.group_code = group
            member.user_status = True
            member.save()

            return redirect('bbs:main')
    else:
        form = GroupForm(instance=new_group)

        return render(request, 'group/group_signin.html', {
            'form': form,
            'invite_code': invite_code
        })


def group_modify(request):
    login_email = request.session['loginObj']
    member = Member.objects.get(user_email=login_email)
    group = get_object_or_404(Group, pk=member.group_code)
    group_members = Member.objects.filter(group_code=member.group_code)
    modify_form = ModifyGroupInfoForm(instance=group)

    if request.method == 'POST':
        group_list = Group.objects.all()
        if (group_list.filter(group_code=request.POST['group_code']).exists()) & (group.group_code != request.POST['group_code']):
            return render(request, 'group/group_modify.html', {'message': '이미 존재하는 그룹 이름 입니다.',
                                                               'modify_form': modify_form,
                                                               'group_members': group_members,
                                                               'group': group
                                                               })

        modify_form = ModifyGroupInfoForm(request.POST, instance=group)
        if modify_form.is_valid():
            group = modify_form.save(commit=False)
            if request.POST.get('group_img', True):
                group.group_img = request.FILES['group_img']
            group.save()

            return redirect('group:group_modify')
        else:
            return render(request, 'group/group_modify.html', {
                'message': '그룹정보 update 실패',
                'modify_form': modify_form
            })

    if request.method == 'GET':
        return render(request, 'group/group_modify.html', {'modify_form': modify_form,
                                                           'group_members': group_members,
                                                           'group': group})


def generate_random_slug_code(length=8):
    """
    generates random code of given length
    """
    return base64.urlsafe_b64encode(
        codecs.encode(uuid.uuid4().bytes, "base64").rstrip()
    ).decode()[:length]


def group_del_member(request, user_id):
    member = Member.objects.get(user_id=user_id)
    default_group = Group.objects.get(group_code='default')
    member.group_code = default_group
    member.user_status = False
    member.save()

    # 해당 유저의 게시글 전부 삭제
    posts = Post.objects.filter(user_id=user_id)
    posts.delete()
    
    # 해당 유저의 댓글 전부 삭제
    comments = Comment.objects.filter(user_id=user_id)
    comments.delete()

    if member.user_email == request.session['loginObj']:
        del (request.session['loginObj'])
        return redirect('/')

    return redirect('group:group_modify')

Paple/group/templates/group/group_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paple</title>
    {#  j-Query CDN  #}
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    {#  Bootstrap CDN  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/account.css">

    <script>
        function group_signin(){
            location.href = '/group/group_signin/'
        }
    </script>

</head>
<body>
<div class="d-lg-flex half">
    <div class="bg order-1 order-md-2" style="background-image: url('/static/image/index.jpg');"></div>
    <div class="contents order-2 order-md-1">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-7">
                    <h3> 지금 바로 <strong> <br> 그룹</strong>에 가입하세요.</h3>
                    <p class="mb-4">친구가 보낸 참여코드가 있다면 <br> 이곳에 입력해주세요.</p>
                    <form method="POST" action="{% url 'group:group_login' %}">
                        {% csrf_token %}
                        {{ message }}
                        <div class="form-group">
                            <label for="invite_code">초대 코드</label>
                            <input type="text" class="form-control" placeholder="초대 코드" name="invite_code" id="invite_code">
                        </div>
                        <button type="submit" class="btn btn-dark" style="margin-top: 20px;">Group In</button>
                    </form>
                    <button type="submit" class="btn btn-dark"
                            onclick="group_signin()" style="margin-top: 20px;">Group Sign in</button>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Paple/group/templates/group/group_modify.html
{% extends 'base.html' %}

{% block container %}
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/account.css">
    <script src="/static/js/accounts.js"></script>

    <div class="d-lg-flex half">
        <div class="bg order-1 order-md-2" style="background-image: url('/static/image/account.png');"></div>
        <div class="contents order-2 order-md-1">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-7">
                        <h3><strong>Group Information</strong></h3>
                        <p class="mb-4"></p>
                        <form method="post" href="{% url 'group:group_modify' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ message }}
                            {% for field in modify_form %}
                                <div>
                                    {{ field.label }}<br>
                                    {{ field }}
                                    <br><br>
                                </div>
                            {% endfor %}

                            <h4>Group member</h4>
                            <br>
                            {% for member in group_members %}
                                <div>
                                    <li>{{ member.user_name }} ({{ member.user_email }}) &nbsp
                                        <button type="button" style="background-color: #e35052; border-color: #e35052; color: white"
                                                class="btn-sm" onclick="group_del_member({{ member.user_id }})"> 삭제 </button>
                                    </li>
                                    <br>
                                </div>
                            {% endfor %}
                            <br><br>
                            <button type="submit" class="btn btn-block btn-primary"> Modify </button>
                            <button type="button" class="btn btn-block btn-primary" onclick="main()"> Main </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Paple/group/templates/group/group_signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paple</title>
    {#  j-Query CDN  #}
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    {#  Bootstrap CDN  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/account.css">
</head>
<body>
<div class="d-lg-flex half">
    <div class="bg order-1 order-md-2" style="background-image: url('/static/image/index.jpg');"></div>
    <div class="contents order-2 order-md-1">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-7">
                    <h3> 참여코드는 [ <strong>{{ invite_code }}</strong> ]입니다.</h3> <br>
                    <p class="mb-4"><strong>새 그룹</strong>을 만들어보세요! </p>
                    <form method="POST" href="{% url 'group:group_signin' %}">
                        {% csrf_token %}
                        {{ message }}
                        {% for field in form %}
                            <div>
                                {{ field.label }}
                                {{ field}}
                                <br>
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-black btn-primary"> Sign In </button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Paple/group/templates/group/preview_imagefield.html
<!-- 기존이미지 -->
<div>
    {% if value %}
        <img id='imagePreview' style="height: 100%; width: 100%"
         src='{{ value.url }}' alt="{{ value.url }}"/>
    {% endif %}

    <!-- 파일 업로드 폼 좀 더 예쁘게(선택사항) -->
    <div class="custom-file">
        <input type="file" id="{{ id }}" class="custom-file-input" name="{{ name }}" accept="image/*" style="cursor: pointer;">
    </div>

    <!-- 여기서부터 스크립트 -->
    <script>

        // 파일 선택 이벤트 등록
        var imgFieldCtrl = document.getElementById('{{ id }}')
        imgFieldCtrl.addEventListener('change', function(e) {
            if (imgFieldCtrl.files && imgFieldCtrl.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('imagePreview').src = e.target.result;
                }

                // convert to base64 string
                reader.readAsDataURL(document.getElementById('{{ id }}').files[0]);
            }
        });
    </script>
</div>