Paple/bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('logout/', views.logout, name='logout'),
    path('board/', views.board, name='board'),
    path('board/<int:post_id>/', views.detail, name='detail'),
    path('board/<int:post_id>/comment/', views.comment_register, name='comment_register'),
    path('board/<int:post_id>/update/', views.post_update, name='post_update'),
    path('board/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('board/register/', views.post_register, name='post_register'),
    path('board/register2/<int:q_id>', views.post_register2, name='post_register2'),
    path('board/<int:q_id>/register/', views.question_register, name='question_register'),
    path('board/<str:q_date>/register2/', views.question_register2, name='question_register2')
]

Paple/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('bbs/', include('bbs.urls')),
    path('account/', include('account.urls')),
    path('group/', include('group.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Paple/bbs/models.py
from django.db import models
from account.models import Member, Group


class Question(models.Model):
    q_id = models.BigAutoField(primary_key=True)
    q_content = models.CharField(max_length=200)
    q_date = models.DateField()

    def __str__(self):
        return self.q_content

    def as_dict(self):
        question_date = self.q_date.strftime('%Y-%m-%d')
        return {'q_content': self.q_content, 'q_date': question_date}


class Post(models.Model):
    post_id = models.BigAutoField(primary_key=True)
    user_id = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='user_id')
    group_code = models.ForeignKey(Group, on_delete=models.CASCADE, db_column='group_code')
    post_date = models.DateTimeField(auto_now_add=True)
    post_name = models.CharField(max_length=30)
    post_content = models.TextField()

    def __str__(self):
        return self.post_name


class Comment(models.Model):
    c_id = models.BigAutoField(primary_key=True)
    user_id = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='user_id')
    group_code = models.ForeignKey(Group, on_delete=models.CASCADE, db_column='group_code')
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, db_column='post_id')
    c_content = models.TextField()

    def __str__(self):
        return self.c_content


# DB 수정사항 반영
# python manage.py migrate <app_name> zero
# python manage.py makemigrations <app_name>
# python manage.py migrate

Paple/bbs/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['post_name', 'post_content']

        labels = {
            'post_name': '제목',
            'post_content': '내용'
        }

        widgets = {
            'post_name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'post_content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 1,
                    'cols': 40,
                    'style': 'height: 20em;'
                }
            )
        }

Paple/bbs/views.py
from django.shortcuts import render, redirect, get_object_or_404

from bbs.models import Question, Post, Comment
from account.models import Group, Member
from django.core.paginator import Paginator
from .forms import PostForm
import datetime


def main(request):
    try:
        user_email = request.session['loginObj']
    except:
        return redirect('/')

    if user_email:
        # 달력 질문 리스트
        questions = Question.objects.all().order_by('q_date')
        q_list = [q.as_dict() for q in questions]

        # 올라온 질문
        member = Member.objects.get(user_email=user_email)
        group_code = member.group_code
        posts = Post.objects.filter(group_code=group_code).order_by('-post_id')[0:2]

        # 오늘의 질문
        today_date = datetime.date.today().isoformat()
        try:
            today_q = Question.objects.get(q_date=today_date)
        except Question.DoesNotExist:
            today_q = None

        return render(request, 'bbs/main.html', {
            'q_list': q_list,
            'posts': posts,
            'today_q': today_q,
        })
    else:
        return redirect('/')


def logout(request):
    if request.session['loginObj']:
        del (request.session['loginObj'])
    return redirect('/')


def board(request):
    # 해당 그룹의 게시판 글을 DB에서 불러옴
    user_email = request.session['loginObj']
    member = Member.objects.get(user_email=user_email)
    group_code = member.group_code
    posts = Post.objects.select_related('user_id').filter(group_code=group_code).order_by('-post_id')

    page = request.GET.get('page', '1')

    # 페이지 당 게시물 개수 지정
    paginator = Paginator(posts, 10)
    page_obj = paginator.get_page(page)

    context = {'posts': page_obj}

    return render(request, 'bbs/board.html', context)


def detail(request, post_id):
    post = Post.objects.select_related('user_id').get(post_id=post_id)

    user_email = request.session['loginObj']
    member = Member.objects.get(user_email=user_email)
    group_code = member.group_code
    comments = Comment.objects.filter(group_code=group_code, post_id=post_id).select_related('user_id')

    return render(request, 'bbs/detail.html', {
        'post': post,
        'comments': comments
    })


def post_register(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            user_email = request.session['loginObj']
            member = Member.objects.get(user_email=user_email)
            group_code = member.group_code

            # member가 아닌 user_email인지 확인 필요
            post.user_id = member
            post.group_code = group_code
            post.post_date = datetime.datetime.now()
            post.save()
            return redirect('bbs:board')
    else:
        form = PostForm()

    return render(request, 'bbs/post_register.html', {
        'form': form
    })


def post_register2(request, q_id):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            user_email = request.session['loginObj']
            member = Member.objects.get(user_email=user_email)
            group_code = member.group_code

            # member가 아닌 user_email인지 확인 필요
            post.user_id = member
            post.group_code = group_code
            post.post_date = datetime.datetime.now()
            post.save()
            return redirect('bbs:board')
    else:
        question = Question.objects.get(q_id=q_id)
        form = PostForm(initial={'post_name': question.q_content})

    return render(request, 'bbs/post_register.html', {
        'form': form
    })


def post_update(request, post_id):
    post = Post.objects.get(post_id=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            user_email = request.session['loginObj']
            member = Member.objects.get(user_email=user_email)
            group_code = member.group_code
            post.user_id = member
            post.group_code = group_code
            post.post_date = datetime.datetime.now()
            post.save()

            return redirect('bbs:detail', post_id=post_id)
    else:
        form = PostForm(instance=post)

    return render(request, 'bbs/post_update.html', {
        'form': form
    })


def post_delete(request, post_id):
    post = Post.objects.get(post_id=post_id)
    post.delete()
    return redirect('bbs:board')


def comment_register(request, post_id):
    if request.method == 'POST':
        val = request.POST.get("comment")
        user_email = request.session['loginObj']
        member = Member.objects.get(user_email=user_email)
        group_code = member.group_code
        post = Post.objects.get(post_id=post_id)

        comment = Comment()
        comment.user_id = member
        comment.group_code = group_code
        comment.c_content = val
        comment.post_id = post
        comment.save()

        return redirect('bbs:detail', post_id=post_id)


def question_register(request, q_id):
    question = Question.objects.get(q_id=q_id)

    user_email = request.session['loginObj']
    member = Member.objects.get(user_email=user_email)
    group_code = member.group_code

    try:
        post = Post.objects.get(post_name=question.q_content, group_code=group_code)
    except Post.DoesNotExist:
        post = None

    if post is None:
        return redirect('bbs:post_register2', q_id=question.q_id)
    else:
        return redirect('bbs:detail', post_id=post.post_id)


def question_register2(request, q_date):
    try:
        question = Question.objects.get(q_date=q_date)
    except Question.DoesNotExist:
        return redirect('bbs:main')

    user_email = request.session['loginObj']
    member = Member.objects.get(user_email=user_email)
    group_code = member.group_code

    try:
        post = Post.objects.get(post_name=question.q_content, group_code=group_code)
    except Post.DoesNotExist:
        post = None

    if post is None:
        return redirect('bbs:post_register2', q_id=question.q_id)
    else:
        return redirect('bbs:detail', post_id=post.post_id)

Paple/main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')

Paple/bbs/templates/bbs/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paple</title>

    <!-- jQuery를 이용하기 위해 CDN 방식을 이용 -->
    <script
            src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous">
    </script>

    <!-- Bootstrap을 이용하기 위해 CDN 방식을 이용-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link rel="stylesheet" href="/static/css/google_font.css">

    <script src="/static/js/main.js"></script>
    <script src="/static/js/board.js"></script>
    <script>
        function post_register(){
            location.href = '/bbs/board/register/'
        }
    </script>

    <script>
        $(document).ready(function(){
            changeColor();
        })

        function changeColor(){
            $('#td_name').mouseover(function(){
                $(this).addClass('changeColor');
            }).mouseout(function() {
                $(this).removeClass('changeColor');
            });
        }
    </script>

    <style>
        .changeColor {
            color: whitesmoke;
        }
    </style>

</head>
<body>
<!-- 상단 navbar -->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" aria-label="Eighth navbar example"
         style="background-color: saddlebrown; opacity: 0.8">
        <div class="container">
            <a class="navbar-brand" href="/bbs/main/">Paple</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarsExample07">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/bbs/board/">그룹 게시판</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/group/modify/">Group Info</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/account/modify/">User Info</a>
                    </li>
                </ul>

                <button class="btn btn-danger btn-lg"
                        style="background-color: antiquewhite; color: saddlebrown"
                        type="submit" onclick="logout()">Logout</button>
            </div>
        </div>
    </nav>
</header>

    <div class="container"  style="margin-top: 100px">
        <table class="table" style="margin-top: 20px">
            <h1>그룹 게시판</h1>
            <thead class="table" style="background-color: BurlyWood; color: saddlebrown">
                <tr>
                    <th>#</th>
                    <th>글 작성자</th>
                    <th>글 제목</th>
                    <th>글 작성 날짜</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>{{ post.post_id }}</td>
                    <td>{{ post.user_id.user_name }}</td>
                    <td id="td_name" style="cursor:pointer; width:40%;"
                        onclick="move_post({{ post.post_id }})">{{ post.post_name }}</td>
                    <td>{{ post.post_date }} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <button class="btn" type="submit"
                style="background-color: BurlyWood; color: saddlebrown"
                onclick="post_register()">새 글 작성하기</button>

        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in posts.paginator.page_range %}
                {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
                    {% if page_number == posts.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link"
                           style="background-color: saddlebrown; color:whitesmoke;" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link"
                           style="background-color: saddlebrown; color:whitesmoke;"
                           href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </div>


</body>
</html>

Paple/bbs/templates/bbs/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paple</title>

    <!-- jQuery를 이용하기 위해 CDN 방식을 이용 -->
    <script
            src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous">
    </script>

    <!-- Bootstrap을 이용하기 위해 CDN 방식을 이용-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link rel="stylesheet" href="/static/css/google_font.css">

    <script src="/static/js/main.js"></script>
    <script src="/static/js/detail.js"></script>

    <script>
        function post_update(post_id){
            location.href = '/bbs/board/'+post_id+'/update/'
        }

        function post_delete(post_id){
            location.href = '/bbs/board/'+post_id+'/delete/'
        }
    </script>

</head>
<body>
<!-- 상단 navbar -->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" aria-label="Eighth navbar example"
         style="background-color: saddlebrown; opacity: 0.8">
        <div class="container">
            <a class="navbar-brand" href="/bbs/main/">Paple</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarsExample07">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/bbs/board/">그룹 게시판</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/group/modify/">Group Info</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/account/modify/">User Info</a>
                    </li>
                </ul>

                <button class="btn btn-danger btn-lg"
                        style="background-color: antiquewhite; color: saddlebrown"
                        type="submit" onclick="logout()">Logout</button>
            </div>
        </div>
    </nav>
</header>

  <div class="container" style="margin-top: 100px">
      <article class="blog-post">
          <h1 class="blog-post-title" style="margin-bottom: 20px">{{ post.post_name }}</h1>
          <div style="float:left; margin-right: 3px">
              <img src="/static/image/calendar_icon.png"
                   style="margin-right: 1px; width: 15px; height: 15px"/>
          </div>
          <div style="float:left; margin-right: 20px">
              <p class="blog-post-meta">{{ post.post_date }}</p>
          </div>
          <div style="float:left; margin-right: 3px">
              <img src="/static/image/user_icon.png"
                         style="margin-right: 1px; width: 15px; height: 15px"/>
          </div>
          <div style="margin-right: 5px">
              <p class="blog-post-meta">{{ post.user_id.user_name }}</p>
          </div>
          <hr>

          <p class="lead"
             style="margin-top: 30px; margin-bottom: 30px">{{ post.post_content|linebreaksbr }}</p>
          <hr>

      </article>
      {% if request.session.loginObj == post.user_id.user_email|stringformat:"s" %}
          <button type="submit" class="btn"
                  style="margin-right: 10px; float: left; background-color: BurlyWood; color: saddlebrown;"
                  onclick="move_board()">게시판으로</button>
          <button type="submit" class="btn"
                  style="margin-right: 10px; float: left; background-color: BurlyWood; color: saddlebrown;"
                  onclick="post_update({{ post.post_id }})">수정하기</button>
          <button type="submit" class="btn"
                  style="background-color: BurlyWood; color: saddlebrown;"
                  onclick="post_delete({{ post.post_id }})">삭제하기</button>
      {% else %}
          <button type="submit" class="btn "
                  style="background-color: BurlyWood; color: saddlebrown;"
                  onclick="move_board()">게시판으로</button>
      {% endif %}


      <!-- Single Comment -->
      <div class="card my-4"  style="margin-top: 30px; margin-bottom: 30px">
          <h5 class="card-header" style="background-color: BurlyWood; color: saddlebrown;">댓글</h5>
          {% if comments %}
              {% for comment in comments %}
                  <div class="card-body">
                      <h5 class="mt-0">{{ comment.user_id.user_name }}</h5>
                      {{ comment.c_content|linebreaksbr }}
                  </div>
              {% endfor %}
          {% else %}
              <div class="card-body">댓글 없음</div>
          {% endif %}
      </div>

      <!-- Comments Form -->
      <div class="card my-4">
          <h5 class="card-header " style="background-color: BurlyWood; color: saddlebrown;">댓글 달기</h5>
          <div class="card-body">
              <form method="POST" action="{% url 'bbs:comment_register' post.post_id %}">
                  {% csrf_token %}
                  <div class="form-group">
                      <textarea class="form-control" rows="3" name="comment"></textarea>
                  </div>
                  <button type="submit" class="btn" style="margin-top: 20px; background-color: BurlyWood; color: saddlebrown;">등록</button>
              </form>
          </div>
      </div>

  </div>

</body>
</html>

Paple/bbs/templates/bbs/post_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paple</title>

    <!-- jQuery를 이용하기 위해 CDN 방식을 이용 -->
    <script
            src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous">
    </script>

    <!-- Bootstrap을 이용하기 위해 CDN 방식을 이용-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link rel="stylesheet" href="/static/css/google_font.css">

    <script src="/static/js/main.js"></script>
    <script src="/static/js/board.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/account.css">
    <script src="/static/js/accounts.js"></script>

    <script>
        $(document).ready(function(){
            changeColor();
        })

        function changeColor(){
            $('#td_name').mouseover(function(){
                $(this).addClass('changeColor');
            }).mouseout(function() {
                $(this).removeClass('changeColor');
            });
        }
    </script>

    <style>
        .changeColor {
            color: #002fff;
        }
    </style>

</head>
<body>
<!-- 상단 navbar -->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" aria-label="Eighth navbar example"
         style="background-color: saddlebrown; opacity: 0.8">
        <div class="container">
            <a class="navbar-brand" href="/bbs/main/">Paple</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarsExample07">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/bbs/board/">그룹 게시판</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/group/modify/">Group Info</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/account/modify/">User Info</a>
                    </li>
                </ul>

                <button class="btn btn-danger btn-lg"
                        style="background-color: antiquewhite; color: saddlebrown"
                        type="submit" onclick="logout()">Logout</button>
            </div>
        </div>
    </nav>
</header>

    <div class="d-lg-flex half">
            <div class="container">
                <div class="row align-items-center justify-content-center" >
                    <div class="col-md-7">
                        <h3>새 글 작성하기</h3>
                        <p class="mb-4"></p>
                        <form method="POST" href="{% url 'bbs:post_register' %}">
                            {% csrf_token %}
                            {{ message }}
                            {% for field in form %}
                             <div>
                              {{ field.label }}
                              {{ field}}
                             <br>
                            </div>
                            {% endfor %}

                            <button type="submit" class="btn btn-black btn-primary"> 작성하기 </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>


</body>
</html>

Paple/bbs/templates/bbs/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paple</title>

    <!-- jQuery를 이용하기 위해 CDN 방식을 이용 -->
    <script
            src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous">
    </script>

    <!-- Bootstrap을 이용하기 위해 CDN 방식을 이용-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link rel="stylesheet" href="/static/css/google_font.css">

    <script src="/static/js/main.js"></script>
    <script src="/static/js/board.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/account.css">
    <script src="/static/js/accounts.js"></script>

    <script>
        $(document).ready(function(){
            changeColor();
        })

        function changeColor(){
            $('#td_name').mouseover(function(){
                $(this).addClass('changeColor');
            }).mouseout(function() {
                $(this).removeClass('changeColor');
            });
        }
    </script>

    <style>
        .changeColor {
            color: #002fff;
        }
    </style>

</head>
<body>
<!-- 상단 navbar -->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" aria-label="Eighth navbar example"
         style="background-color: saddlebrown; opacity: 0.8">
        <div class="container">
            <a class="navbar-brand" href="/bbs/main/">Paple</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarsExample07">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/bbs/board/">그룹 게시판</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/group/modify/">Group Info</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link" href="/account/modify/">User Info</a>
                    </li>
                </ul>

                <button class="btn btn-danger btn-lg"
                        style="background-color: antiquewhite; color: saddlebrown"
                        type="submit" onclick="logout()">Logout</button>
            </div>
        </div>
    </nav>
</header>

    <div class="d-lg-flex half">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-7">
                        <h3>글 수정하기</h3>
                        <p class="mb-4"></p>
                        <form method="POST" href="{% url 'bbs:post_register' %}">
                            {% csrf_token %}
                            {{ message }}
                            {% for field in form %}
                             <div>
                              {{ field.label }}
                              {{ field}}
                             <br>
                            </div>
                            {% endfor %}

                            <button type="submit" class="btn btn-black btn-primary"> 수정하기 </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>

</body>
</html>